POST http://127.0.0.1:3000/rideRequest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2ODgyMTMxODIsImV4cCI6MTY4ODIxNjc4Mn0.I15Ey_U0jzHJW7_bF78cyYT2hm6GQGP7gg4m8D4V3cM
Content-Type: application/json

{
    "startLocation": [0, 2.05],
    "destinationLocation": [0, 2],
    "cargoWeight": 1,
    "cargoVolume": 1,
    "cargoDescription": "test",
    "cargoSpecialCharacteristics": ""
}

